In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
from scripts.ml_helper import CodonDataset

codondataset = CodonDataset("E.Coli")

In [3]:
aa, codon = codondataset[0]
print(aa)
print(codon)

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 

In [4]:
generator = torch.Generator().manual_seed(42)
train_set, val_set = torch.utils.data.random_split(codondataset, [0.8, 0.2], generator=generator)

In [5]:
print(len(train_set))
print(len(val_set))

3085
771


In [6]:
train_set[0]

(tensor([[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 1]]),
 tensor([35, 19, 32, 40, 32, 60, 28,  3,  2, 35, 17, 13, 48, 15, 62,  0,  2, 33,
         17, 41, 19, 51, 24, 21,  1, 22, 29, 23, 19, 40, 33,  1, 48, 41, 51, 55,
         19, 32,  0, 37, 51, 19, 35, 24, 60, 35, 27, 19, 55, 18,  3, 42,  5, 36,
          2, 23, 42, 56, 61, 23, 27, 35, 37, 37, 53, 58, 43, 50, 31, 32,  1, 16,
          1, 61, 51,  0, 58, 19, 19, 53, 15, 27, 43, 42,  0, 42, 48, 42, 42, 10]))