In [1]:
import pandas as pd
%load_ext autoreload
%autoreload 2

In [2]:
import torch
from scripts.ml_helper import CodonDataset

codondataset = CodonDataset("E.Coli")

In [3]:
aa, codon = codondataset[0]
print(aa)
print(codon)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [4]:
generator = torch.Generator().manual_seed(42)
train_set, val_set = torch.utils.data.random_split(codondataset, [0.8, 0.2], generator=generator)

In [5]:
print(len(train_set))
print(len(val_set))

3085
771


In [6]:
train_set[0]

(tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 1.]]),
 tensor([35., 19., 32., 40., 32., 60., 28.,  3.,  2., 35., 17., 13., 48., 15.,
         62.,  0.,  2., 33., 17., 41., 19., 51., 24., 21.,  1., 22., 29., 23.,
         19., 40., 33.,  1., 48., 41., 51., 55., 19., 32.,  0., 37., 51., 19.,
         35., 24., 60., 35., 27., 19., 55., 18.,  3., 42.,  5., 36.,  2., 23.,
         42., 56., 61., 23., 27., 35., 37., 37., 53., 58., 43., 50., 31., 32.,
          1., 16.,  1., 61., 51.,  0., 58., 19., 19., 53., 15., 27., 43., 42.,
          0., 42., 48., 42., 42., 10.]))

In [7]:
from Bio.SeqRecord import SeqRecord


def convert_record_to_string(rec: SeqRecord) -> str:
    return str(rec.seq)


In [8]:
from numpy.core.defchararray import zfill

df = codondataset.df["translation"].apply(convert_record_to_string)
df.head()

0                               MKRISTTITTTITITTGNGAG*
1    MRVLKFGGTSVANAERFLRVADILESNARQGQVATVLSAPAKITNH...
2    MVKVYAPASSANMSVGFDVLGAAVTPVDGALLGDVVTVEAAETFSL...
3    MKLYNLKDHNEQVSFAQAVTQGLGKNQGLFFPHDLPEFSLTEIDEM...
5    MLILISPAKTLDYQSPLTTTRYTLPELLDNSQQLIHEARKLTPPQI...
Name: translation, dtype: object

In [9]:
cds = CodonDataset("E.Coli", padding="left")
cds.df.head()

id  \
0  lcl|U00096.3_cds_AAC73112.1_1   
1  lcl|U00096.3_cds_AAC73113.1_2   
2  lcl|U00096.3_cds_AAC73114.1_3   
3  lcl|U00096.3_cds_AAC73115.1_4   
5  lcl|U00096.3_cds_AAC73117.1_6   

                                         description  \
0  lcl|U00096.3_cds_AAC73112.1_1 [gene=thrL] [loc...   
1  lcl|U00096.3_cds_AAC73113.1_2 [gene=thrA] [loc...   
2  lcl|U00096.3_cds_AAC73114.1_3 [gene=thrB] [loc...   
3  lcl|U00096.3_cds_AAC73115.1_4 [gene=thrC] [loc...   
5  lcl|U00096.3_cds_AAC73117.1_6 [gene=yaaA] [loc...   

                                            sequence  \
0  (A, T, G, A, A, A, C, G, C, A, T, T, A, G, C, ...   
1  (A, T, G, C, G, A, G, T, G, T, T, G, A, A, G, ...   
2  (A, T, G, G, T, T, A, A, A, G, T, T, T, A, T, ...   
3  (A, T, G, A, A, A, C, T, C, T, A, C, A, A, T, ...   
5  (A, T, G, C, T, G, A, T, T, C, T, T, A, T, T, ...   

                                         translation  \
0                             MKRISTTITTTITITTGNGAG*   
1  MRVLKFGGTSVANAERFLRVADILESNARQGQVATVLSAPAKITNH...   
2  MVKVYAPASSANMSVGFDVLGAAVTPVDGALLGDVVTVEAAETFSL...   
3  MKLYNLKDHNEQVSFAQAVTQGLGKNQGLFFPHDLPEFSLTEIDEM...   
5  MLILISPAKTLDYQSPLTTTRYTLPELLDNSQQLIHEARKLTPPQI...   

                        seguid  
0  QuAqLUJXXhVXIJRPc+T7iMi0UqE  
1  /p+3Jdgat4Fq0w2rqqay4xg8Bs4  
2  scFdp6oP+pW5HnvUww8MSi93ntM  
3  EkFurFHdk7l6qKQ+5xRiBUhWM9U  
5  vJJ0yR31YORqwI12U79SgItYU3U